#!/bin/bash
#
# Functional testing
#

. .zbuild/scripts/functest/common.sh

echo "Testing zbuild in dir $ZBUILD_DIR"

rm -rf $WD
mkdir $WD

pushd $WD

$ZEB $ARGS init 

# Import the test scripts
$ZEB $ARGS sync $ZBUILD_DIR/test/scripts/
if [ "$?" != "0" ]; then echo "ERROR: could not sync scripts"; fi

exit 0

test/run_all_tests.sh


# 1, testing here in my worktree
#      unit testing
#      booting a system in worktree and test functions
# 2, testing staging
#      unit testing
#      booting a system from packs and test functions
# 3, testing prod
#      test safe functions




1 build + unit test work tree
2 build + func test work tree
3 build + deb_pack + install + unit test + func test staging
4 install + safe func test prod


1: zbuild unittest
2: zbuild functest
3: zbuild stage -h host.dk
4: zbuild release