#!/bin/bash
#
# If the software contains a 'debian' directory ie. can be build as a
# debian package then this command will build the debian package(s)
#

# zbuild_build_debian_package <repos name>
# e.g.
# zbuild_build_debian_package zbuild.git

